- src/config.c
Hi pev developers,
config.c does not build at the moment on NetBSD. It makes use of the "PATH_MAX" constant, which according to POSIX should be available from &lt;limits.h&gt;. Another version of this fix would therefore be to unconditionally include this header instead - I simply cannot tell if it really is available on every platform you support at the moment.
Generally wise, I believe it is best to not rely on PATH_MAX to allocate fixed-size buffers for filenames anyway, because some systems do not have any such limitation in the first place.
HTH,
-- khorben
> Fixed building config.c on NetBSD

- Makefile
Hi pev developers,
as far as I know the $(MAKE) variable is automatically created by the underlying make(1) program in use. It is therefore harmful to enforce it this way, and it breaks the build on platforms where GNU make is not directly available as "make" (such as NetBSD).
In any case, you do require GNU make and it does set $(MAKE), so this change should be safe.
HTH,
-- khorben
> No longer force a specific make(1) program

- src/plugins/json.c
This is a fix for a minor issue where the various pev tools generate illegal JSON (when used with -f json) in the form of a missing comma.  A comma is omitted where the scope (e.g., an array) it would apply to is empty.
Here is an example of the problem when running readpe on a particular sample:
```json
...snip...
},
"Optional/Image header": {
"Magic number": "0x10b (PE32)",
"Linker major version": "6",
"Linker minor version": "0",
"Size of .text section": "0x2d000",
"Size of .data section": "0x99a00",
"Size of .bss section": "0",
"Entrypoint": "0xc8000",
"Address of .text section": "0x1000",
"Address of .data section": "0x1000",
"ImageBase": "0x400000",
"Alignment of sections": "0x1000",
"Alignment factor": "0x200",
"Major version of required OS": "4",
"Minor version of required OS": …
```
> Fix missing commas in JSON output

- src/output.c
If `parent_scope` is declared as const, the compiler may emit code that assumes the value doesn't change, i.e. dereferencing the null pointer.
https://bugs.debian.org/868554
> Remove const qualifier from parent_scope

- src/pehash.c
The extra byte is needed for the terminating null byte.
> Fix off-by-one buffer overflow in imphash()

- src/pehash.c
Fixes buffer overflow in `imphash()`.
> Fix imphash_string buffer size calculation

- src/pehash.c
From the `snprintf` manpage:
> Some programs imprudently rely on code such as the following
>
>     sprintf(buf, "%s some further text", buf);
>
> to append text to buf. However, the standards explicitly note that the results are undefined if source and destination buffers overlap when calling `sprintf()`, `snprintf()`, `vsprintf()`, and `vsnprintf()`. Depending on the version of gcc(1) used, and the compiler options employed, calls such as the above will not produce the expected results.
> Fix misuse of sprintf() in imphash()

- src/pev.conf
- src/plugins.c
[root@localhost src]# uname -a
Linux localhost.localdomain 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost src]# cat pev.conf
plugins_dir=/usr/local/lib/pev/plugins
[root@localhost src]# ls -l /usr/local/lib/pev/plugins/
total 76
-rwxr-xr-x 1 root root 12560 Aug 11 18:07 csv_plugin.so
-rwxr-xr-x 1 root root 12744 Aug 11 18:07 html_plugin.so
-rwxr-xr-x 1 root root 12696 Aug 11 18:07 json_plugin.so
-rwxr-xr-x 1 root root  8416 Aug 11 18:07 text_plugin.so
-rwxr-xr-x 1 root root 12688 Aug 11 18:07 xml_plugin.so
[root@localhost src]# ./build/readpe /home/liyl/ent_samples/0222.exe
readpe: output.c:242: output_open_document_with_name: Assertion `g_format != ((void *)0)' failed.
Aborted (core dumped)
> fix readdir bug for linux

- include/common.h
- src/peres.c
Added some support for named resources:
`peres -l test.exe` prints a short list of all data entries and their names/ids.
`peres -X test.exe` uses these names for the extracted files.
> peres: Added list view and named extraction

- include/common.h
- src/pepack.c
strncpy(3) needs 1 more byte for NUL character.
gcc barfs on current code-base:
> warning: '__builtin_strncpy' specified bound 80 equals destination size [-Wstringop-truncation]
>  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
Also, per comment in https://github.com/merces/pev/pull/154#issuecomment-762512111
MAX_MSG should be 81 not 80.
> repack: allocate 1 more byte for NUL character

- src/Makefile
The build systems of some Linux distros (like Debian) make use of
_FORTIFY_SOURCE in more secure levels than stated by pev. This patch
only defines _FORTIFY_SOURCE if it has not been defined before.
The previous approach of undefining and defining it unconditionally
caused a weakening of the hardening expected by those distros' build
systems. This patch keeps the same functionality as before, while
allowing for distros to use more secure levels if so they wish.
> Avoid undefining _FORTIFY_SOURCE unnecessarily

- src/Makefile
Some Linux distributions (such as Debian [1]) are striving to make their
build reproducible.
The usage of filesystem globbing as an input to the make build might
cause inconsistencies due to differences between locales [2]. This
inconsistent behavior prevents reproducible builds.
This patch sorts the Makefile inputs to ensure they will be always
processed in the same order [3], contributing to the build system
reproducibility.
[1] https://wiki.debian.org/ReproducibleBuilds
[2] https://reproducible-builds.org/docs/stable-inputs/#fn:sorted-wildcard
[3] https://reproducible-builds.org/docs/stable-inputs/
> Sort Makefile inputs to make build reproducible

- src/config.c
- src/plugins.c
Just a small merge request.
The pelib submodule was broken (updated to libpe master)
Further two small memory leaks were closed:
- `plugins.c`: in which asptintf allocations were not freed every cycle; The man page says it should use realloc but valgrind reported it as malloc and thus as a leak  and I tend to trust produced code more than the documentation.
- `config.c`: Man pages states that the line pointer has to be freed even on failure/no read.
> Fix submodule link and close memory leaks

- src/Makefile
- src/config.c
Fixing:
- A compiler warning when compiling, because of "unsafe" `case` statements (without `break` statements)
- `vsnprintf()` could destroy the va_list content on some implementations, using the same argument list could cause an undefined behaviors or a clash (SIGSEGV)
> Fixing a possible UB inside of `asprintf`

- lib/libpe/Makefile
- src/plugins.c
- src/plugins/Makefile
This patch fixes the build on Debian GNU/Hurd and Debian kFreeBSD distros by detecting the respective $PLATFORM_OS and compiler predefined macros and acting accordingly.
> Fix build on Debian GNU/Hurd & kFreeBSD

- src/pestr.c
Instead of having a write buffer for pestr I track string starting positions for utf8/ascii, utf16 (odd start byte), and utf16(even start byte). I also do an explicit byte swap since C uses big endian but PE uses little endian.
This might add more "fake" strings in the 1 to 2 character range but also stops these to interfere with other types of strings.
This fixes #142
> Fix UTF-16LE strings not being detected properly

- lib/libpe/Makefile
pescan does not actually use the math library itself but libpe does.
This causes no issues as when libpe wants to use the math library it is already loaded by pescan.
Compiling with `-Wl,--as-needed` filters out unneeded linking and since the math library is not needed in pescan and not linked into libpe it will be removed. Thus throwing a missing symbol `_[mangaled stuff]_log2`.
This can easily be manually fixed on older versions by adding `-lm` to `LDFLAGS`.
So for example `LDFLAGS="${LDFLAGS} -Wl,--as-needed -lm" make`
> Fix compilation with -Wl,--as-needed

- src/pesec.c
> When the /guard:cf Control Flow Guard (CFG) option is specified, the compiler and linker insert extra runtime security checks to detect attempts to compromise your code.
https://learn.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-170
https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard
https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#dll-characteristics
> Show CFG status on pesec

- lib/libpe/pe.c
Insert \0 on 9th+ character instead of the 8th.
The issue comes down to section names that are exactly 8 characters long do not have a terminating `\0`.
The code already added a `\0` but applied it always to the 8th character instead of the last character of the write buffer. (which needs to be 9 characters long).
fixes #195
> fix 8 character long section names being cut off

- lib/libpe/pe.c
pe_section_name accidentally replaces the last character in section names that are 8 bytes long with a NUL. This results in a section header name like `.cmdline`[1] being printed as `.cmdlin`.
This addresses the off-by-one issue by ensuring we have a NUL at the end of our buffer (which is >= 9 bytes) instead putting it at the byte before the end.
[1]: https://uapi-group.org/specifications/specs/unified_kernel_image/
> fix printing section names that are 8 bytes long

- README.md
I did not really find this install info in the readme or [user manual](https://pev.sourceforge.io/doc/manual/en_us/) so had to figure out myself. This info might help others in the future who wish to compile and install from source. I tested it both under Fedora and Ubuntu and worked properly.
> Add Linux install info to readme

- lib/libpe/Makefile
- src/Makefile
Fixes #205 
With this PR the `_FORTIFY_SOURCE` level will be left to be handled by the distros default from now on. The previous approach could potentially downgrade the `_FORTIFY_SOURCE` level, especially if the compiler was internally setting it (i.e., not via `CPPFLAGS`), leading to unintended security configurations.
> Remove _FORTIFY_SOURCE definitions

- .github/workflows/multi-os-build.yml
- lib/libpe/hashes.c
- lib/libpe/imports.c
- lib/libpe/include/libpe/pe.h
* Fix ordinal mask bug in imports.c
* Refactor ordinal mask handling
> Fix bug in libpe ordinal mask handling

- lib/libpe/Makefile
- src/plugins/Makefile
macOS requires an absolute path in the install name. Also, use `-bundle` for plugins which is preferred for loadable modules.
> Fix library install name and plugin type on macOS

- Makefile
- README.md
Cygwin updated a library and this broke the Makefile. This PR fixes it and updates the README file accordingly.
> Update build instructions on Windows
